// Builds the Cloudflare Worker for spike S2's two-device test (add-ons design §18, architecture §7): it serves
// net.html at /a and /b, the kit's BIP-340 signer at /schnorr.js, and logs each device's result for `wrangler tail`.
//
//   node examples/phone-test/build.mjs          writes examples/phone-test/worker/ (git-ignored)
//   cd examples/phone-test/worker && npx wrangler deploy        (needs a Cloudflare login and a workers.dev subdomain)
//   npx wrangler tail --format json                              (in another terminal: the results)
//   node ../links.mjs <your-worker-origin>                       three pairs of links (a: this Mac, b: the phone)
//   npx wrangler delete                                          when you are done
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { build } from "esbuild";

const here = new URL(".", import.meta.url).pathname;
const signer = await build({
  entryPoints: [`${here}../../kit/src/schnorr.ts`],
  bundle: true,
  minify: true,
  format: "iife",
  globalName: "Schnorr",
  write: false,
  target: ["es2022"],
});
const js = signer.outputFiles[0].text;
const html = readFileSync(`${here}net.html`, "utf8");
mkdirSync(`${here}worker/src`, { recursive: true });
writeFileSync(
  `${here}worker/src/index.js`,
  `// Generated by examples/phone-test/build.mjs. Serves the two-device test page and logs each device's report.
const HTML = ${JSON.stringify(html)}, JS = ${JSON.stringify(js)};
export default { async fetch(req) {
  const u = new URL(req.url);
  if (u.pathname === "/report") { console.log(decodeURIComponent(u.search.slice(1))); return new Response("{}", { headers: { "Content-Type": "application/json" } }); }
  if (u.pathname === "/schnorr.js") return new Response(JS, { headers: { "Content-Type": "text/javascript; charset=utf-8" } });
  if (u.pathname === "/a" || u.pathname === "/b") return new Response(HTML, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
  return new Response("Not found", { status: 404 });
} };
`,
);
writeFileSync(
  `${here}worker/wrangler.toml`,
  'name = "pipeup-s2-spike"\nmain = "src/index.js"\ncompatibility_date = "2026-09-01"\nworkers_dev = true\n',
);
console.log("wrote examples/phone-test/worker/ (deploy it with `npx wrangler deploy` from there)");
