// The UI's internal property names, shortened in the bundles (never public API, never stored or sent).
// Add a name here only if no public type, stored op or DOM API uses a property of that name. A test keeps the
// add-on API's names (PUBLIC_NAMES) out of it: an add-on built separately would write `menu` where the core reads `a`.
// `navigate` here is Here.navigate; never use it for the Navigation API (window.navigation.navigate).
const INTERNAL =
  "menuRows|rev|notes|statuses|toolList|frames|uis|subs|overlays|undo|queue|uiKey|statusText|rowFor|setIn|addTool|addTo|own|heard|pump|uiState|notice|addSay|ovFor|addSheet|onTick|onSnap|panel|isWriting|showResolved|commenting|listing|reading|draft|quoteAt|readsAt|owns|claim|claimed|focusReply|startDraft|moveDraft|draftEmpty|keepCaret|postDraft|cancelDraft|setCommenting|dismiss|registerDraft|toast|report|pulse|render|frame|layer|pending|actions|visible|hideLabel|setLabel|isEmpty|caret|onSend|onCancel|want|toggleResolved|picking|gutter|fade|room|drawn|grouped|viewport|box|popovers|variant|active|hot|menu|here|holds|navigate|elsewhere|recheck|el|up|level|say|hideHint|back|cursor|away|resume|refocus|backToDraft";

export const MANGLED = new RegExp(`^(${INTERNAL})$`);

/** Every property name of the add-on API (add-ons design §4). None may be mangled. */
export const PUBLIC_NAMES = [
  "use",
  "off",
  "addons",
  "ops",
  "merge",
  "me",
  "threads",
  "sign",
  "signal",
  "ephemeral",
  "has",
  "api",
  "version",
  "document",
  "root",
  "addMenuItem",
  "notify",
  "announce",
  "setComposerNote",
  "setThreadNote",
  "setThreadMark",
  "addComposerTool",
  "openPanel",
  "addStyles",
  "setStatus",
  "overlay",
  "onFrame",
  "where",
  "isHere",
  "go",
  "onUi",
  "avatar",
  "onChange",
  "id",
  "needs",
  "setup",
  "network",
  "when",
  "to",
  "says",
  "state",
  "reason",
  "label",
  "hint",
  "checked",
  "count",
  "select",
  "icon",
  "update",
  "remove",
  "onClose",
  "close",
  "text",
  "people",
  "key",
  "name",
  "view",
  "shown",
  "commentMode",
  "allOpen",
  "dark",
  "writing",
  "kind",
  "thread",
  "focus",
  "connected",
  "setPressed",
  "dictate",
  "commit",
  "cancel",
  "onEnd",
  "press",
  "available",
];
